### PR TITLE
Upgrade Babel to v6.X

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)

Upgrades the babel version to the latest stable release.
#### What tests does this PR have?

None
#### How can this be tested?

The best way to test this is to run `npm run trans` that should babelify the static sit generator. If succesful we are all good. 
#### What domains are affected?

None - This is just the generator
#### What gif best describes how you feel about this work?

OH YEA

---

**Notes when reviewing Static Site Generator projects, please think carefully about what can be done to centralise common functionality. Please also pay attention to anything configurable that will also need updating in the Yeoman generator template**
- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.
#### Reviewers

**Review 1**
- [x] :+1:

**Review 2**
- [x] :+1:

**Review 3**
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

### CODE REVIEW

**Comment by jameshhx** [comment]
Taking :one:

**Comment by Joezo** [comment]
taking 2

**Comment by Joezo** [comment]
looks like it works to me 👍

**Comment by jameshhx** [comment]
Looks good here 👍

**Comment by elliottcrush** [comment]
3️⃣  All good, just need to bump a version.

**Pull request merged**
