### PR TITLE
Updating node version

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- Moves SSG to the latest stable version of node
- Adds an NVM file to ensure node 4+ is used.
#### What tests does this PR have?

None
#### How can this be tested?

See if it compiles, see if it runs
#### Screenshots / Screencast

(none)
#### What gif best describes how you feel about this work?

NEVER UPDATE

---
- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the Tripapplite [contributing document](../CONTRIBUTING.md) and I'm happy for this to be reviewed.
#### Reviewers

**Review 1**
- [x] :+1:

**Review 2**
- [x] :+1:

**Review 3**
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

### CODE REVIEW

**Comment by elliottcrush** [comment]
1️⃣

**Comment by elliottcrush** [comment]
You'll also need to bump the version with this.

**Comment by elliottcrush** [comment]
Works fine for me. 👍

**Comment by Joezo** [comment]
looks okay 👍

**Comment by dancork** [comment]
3️⃣

**Comment by dancork** [comment]
Looks good. One thing that might be worth noting...

https://cloudup.com/csE_Wsks9xh

The marked one is an issue in that the project isn't being maintained. I put a PR in to metalsmith-markdown back in March to change it over to using kramed but had no response... https://github.com/segmentio/metalsmith-markdown/pull/18. Might be worth trying my fork to see if that fixes 2 of the 3 HIGH warnings.

For this PR though that's out of scope so 👍

**Comment by jodiedoubleday** [comment]
I'll raise that as an issue.

**Pull request merged**
